# FooterVerse — Premium Footer Marketplace for Shopify
# https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0d9f4e3d26cc8a711c140b923b03d7ec"
application_url = "https://hyper-foot-shopify-app.vercel.app"
embedded = true
name = "FooterVerse"

[access_scopes]
scopes = "write_themes,read_themes"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://hyper-foot-shopify-app.vercel.app/auth/callback",
  "https://hyper-foot-shopify-app.vercel.app/auth/shopify/callback"
]

[build]
automatically_update_urls_on_dev = true
